### PR TITLE
Add update function

### PR DESCRIPTION
**Pull request by nkatzman**
This PR is implementing the update function exposed by the base class

The function:
1. Get's data from the imdb
2. If the data does not exist, returns null (404 case)
3. Merges the data already in the datastore with what wants to be updated
4. Calls back with the merged data

Updates the version number to 1.0.0

### CODE REVIEW

**Comment by tkyi** [comment]
👍 LGTM
giphy

**Comment by tkyi** [comment]
👍 still LGTM

**Comment by FenrirUnbound** [comment]
👍 

Looks good to me

qhdb9bv

**Comment by d2lam** [comment]
Looks good 👍

**Pull request merged**
